ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/keys/group2_private_key.pem"
GITHUB_WEBHOOK_SECRET: "{{ vault_github_webhook_secret }}"
aws_access_key_id: "{{ vaul_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"