$ANSIBLE_VAULT;1.1;AES256
66356237653934353634663434313431373035653134616663633166623339663137316235323138
3266613966356233626266333066656361326436373864610a653962336339666535343865623463
39613661653765303532346465636666356138303831316535666465663633353239386261633761
3561383837343161350a343733316536373463656536393533346339336434383039306465373837
63666362333538653033343533396231353738323866323431333637353362396634383938343534
66343338333566323937656130363436643438653362633663363532613539366265643035363163
31306535333332663238663764613765643338336232636162303863313364626434616635623432
64616662343537396531396336323333646434383536636333386131356665326433326537663761
63616230373062346631616331363433303931353062363964373731663536343231393736313036
62393035386566306333343165636366636530363233663234383636363366313033353536646462
37333733323964633264383234313437356663316236303835643833636633303433666236633437
37636464626563303366623563383864633734356332333332333536666165643864336466383433
63303433396130356662343331656266636562353731616163616661336433636562623765333232
38306531316665376436323037373431353337323063333335643364333261616632303565663430
61343331316561363933396263356137376137343638383862643138323331333932366165363633
63346338373165343062323864623432623633316337326333663533366666316431383136653635
62323237623461343839623963633630616461396666333836343937646666343832393931386630
62646661313637623633353731623564353539373535366561363835643239383162326166626636
39333239366233303232346162623139626638656638336565613730316563313561313231626134
32613566353330326434633866626132636538366434356536393566653734643263363330356333
37663233363061376237386538666334383062636238326230386639393639306438626432363331
33393134306361633131633738653765373735636136323265353034373934326632663465646636
38666265333936343337396265313731383937373538656363393461623061313539313538633462
31333838373265343333653832376362316639323763383239396536643932663633363138613964
3033
