$ANSIBLE_VAULT;1.1;AES256
39376561303536306332343739623832323661343830323136303731643065323263623037313336
3030653037643939386631396564666138356233663738360a363439653661386664323136336139
36343639306436396461653139316635323365336662323537306261326333326463343937346233
6361663063306163340a633138393439643264323530643165353536346536386665376331373733
6332
