$ANSIBLE_VAULT;1.1;AES256
38323235356234356138353365626563333631363439303030646264653436323230636133356330
6663383138346562323733393538346231333762303536340a393137336637346436303831613432
39373833373438323736393765373537346438613336326530383535356464363231636238316266
3765316662613561340a633731643135613436376165623665373437653661346436353134333134
38313966313333653863383966363366343961306633373066303532636161666461363137393839
66303666393133653939386466376432363137323962373731633032303564373261383635643632
31356630373034656631363337656239626436626437643038356432396139373864353139363434
62356536346530346661646462363836343631646334316265326161376462343634623961366431
65353464653264386466313165306532653431396363333433323931636665346165353135666565
31323064616339656463646166396266313264386635623833623062343765313438346336383337
32326437323738353162353335613139613239386130393835306362626165626261626234646233
37646563373361356534313330323336613730653337626130343934613065316661336332653830
36643932313438326634333237313335303634333639373266623837633433393965656637323065
36623236396366616637633835336438666233303235316664356663656261383138333530636564
39316438363663656563643437313363653262646234393939616235323830366261366266346638
35643063643439636631366330646266386562643230356639636339336430366361316337356336
38303565613565323438663331643038336434383236383862623230386364633230303535653332
65656635663864393337303031393534323665353637393533636165356565366234653838376462
33366530303033316466626561626333353734303030363934613937643832616634366565363530
37306564333963633665623139646433663132626630663337643331346135376133323137666264
63313434616664616137353135306637616361646465386136386566626136313064383362663066
66346635626234393261353638613366373266656132396638383562353832643465316138336431
31636137343362623738623065643239653966366332633263376538363938653762663830383261
39326232613737363563
