plugin: amazon.aws.aws_ec2

regions:
  - us-east-2

filters:
  instance-state-name: running
  tag:Name: "group2-*"

hostnames:
  - public_ip_address
  - private_ip_address

compose:
  ansible_host: public_ip_address
  ansible_host_private: private_ip_address

keyed_groups:
  - key: tags.Name
    prefix: ""