# JCasC
configuration-as-code

# Credentials
credentials
plain-credentials
ssh-credentials

# Git + SCM
git
github
git-client
github-branch-source

# Pipeline
workflow-aggregator
pipeline-utility-steps

# Job DSL 
job-dsl

# Docker (modern working set)
docker-workflow
docker-commons
docker-build-step

# Notifications
email-ext
mailer

# Utilities
timestamper
build-timeout
ws-cleanup
ansicolor

# Build/Test
junit
htmlpublisher
warnings-ng

# UI
blueocean
dashboard-view
cloudbees-folder
