###Jenkins Plugin Installation Configuration###
###Plugins to be installed automatically via jenkins-plugin-cli###

# JCasC
configuration-as-code
configuration-as-code-support

# Credentials
credentials
plain-credentials
ssh-credentials

# Git + SCM
git
github
git-client
github-branch-source

# Pipeline
workflow-aggregator
pipeline-utility-steps

# Job DSL 
job-dsl

# Docker 
docker-workflow
docker
docker-plugin
docker-commons

# Notifications
email-ext
mailer

# Utilities
timestamper
build-timeout
ws-cleanup
pipeline-utility-steps
ansicolor

# Build/Test
junit
htmlpublisher
cobertura
warnings-ng

# UI
blueocean
dashboard-view
cloudbees-folder

# Agent/Node
ssh-slaves
jnlp-slaves

# Security
matrix-auth
role-strategy